Repository slid-to-do/slid-to-do-fe, pull requests merged in 2025-07, with the labels that each got.

#7 [Fix] lint: console, 함수・변수명 겹침 버그 수정
  .github/workflows/feature_action.yml
  .github/workflows/labeler.yml
  src/app/error.tsx
Labels: bug

#8 [Fix] Auto Label fix
  .github/workflows/labeler.yml
Labels: bug

#9 [Feature] CI 기능 추가
  .github/labeler-config.yml
  .github/workflows/dev_action.yml
  .github/workflows/feature_action.yml
  .github/workflows/labeler.yml
  README.md
  package.json
  src/app/error.tsx
Labels: feature

#28 [Feature] 필터 라벨 개수 추가
  .github/labeler-config.yml
Labels: feature

#29 Feat: useModal - 모달 공용 커스텀 훅
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/providers/modal-provider.tsx
  src/hooks/use-modal.tsx
  src/store/use-modal-store.tsx
Labels: feature

#30 [Feature] useModal - 모달 공용 커스텀 훅
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/providers/modal-provider.tsx
  src/hooks/use-modal.tsx
  src/store/use-modal-store.tsx
Labels: feature

#31 [Feat] api 통신 공통 함수
  src/lib/api.ts
  src/types/api.ts
Labels: feature

#48 [Bug] api 통신 결과 코드에 따른 에러처리 로직 수정
  src/lib/api.ts
Labels: bug

#47 [Feature] 할 일 모아보기 페이지 구현
  eslint.config.mjs
  public/todos/ic-checkbox-active.svg
  public/todos/ic-checkbox-inactive.svg
  public/todos/ic-close.svg
  public/todos/ic-delete.svg
  public/todos/ic-file.svg
  public/todos/ic-flag.svg
  public/todos/ic-goal.svg
  public/todos/ic-link.svg
  public/todos/ic-menu.svg
  public/todos/ic-note.svg
  src/app/todos/filter.tsx
  src/app/todos/page.tsx
  src/components/common/modal/side-modal.tsx
  src/components/common/todo-item.tsx
Labels: feature

#52 [Bug] api 통신 에러시 status 반환 코드 추가
  src/lib/api.ts
Labels: bug

#55 [Feature] 목표 상세 페이지 타입 수정
  eslint.config.mjs
  package-lock.json
  package.json
  public/goals/Meatballs_menu.svg
  public/goals/file.png
  public/goals/flag-goal.png
  public/goals/ic_arrow_right.png
  public/goals/ic_plus.svg
  public/goals/kebab.png
  public/goals/link.png
  public/goals/note-view.png
  public/goals/note.png
  src/app/globals.css
  src/app/goals/[goalId]/page.tsx
  src/app/goals/[goalId]/prograss-motion.tsx
  src/components/common/todo-item.tsx
  src/hooks/use-infinite-scroll.ts
  src/types/goal.ts
  src/types/goals.ts
  src/types/notes.ts
  src/types/todos.ts
Labels: feature

#58 [Feature] TanStack Query 무한스크롤 구현
  src/app/goals/[goalId]/page.tsx
  src/hooks/use-infinite-scroll.ts
  src/types/infinite-scroll.ts
Labels: feature

#60 [Fix] 할일 제거 함수 내 타입 에러 해결
  src/app/todos/page.tsx
Labels: bug, Fix

#61 [Bug] api 통신 결과 204번 코드일 경우 로직 추가
  src/app/goals/[goalId]/page.tsx
  src/components/common/modal/two-buttom-modal.tsx
  src/lib/api.ts
Labels: bug

#62 [Fix] 사이드바 애니메이션 버그 이슈 수정 및 tailwind animation 추가
  eslint.config.mjs
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/components/navigation/components/client-sidebar.tsx
  src/components/navigation/components/goal-list.tsx
  src/components/navigation/sidebar-container.tsx
  src/components/navigation/util/motion-variants.tsx
  src/components/style/hamburger-toggle.tsx
  src/hooks/use-layout.tsx
  src/types/sidebar.ts
  tailwind.config.ts
Labels: bug, Design, Fix

#57 [Feature] 회원가입, 로그인 페이지
  package-lock.json
  package.json
  public/common/img-logo.svg
  public/input/ic-eye-off.svg
  public/input/ic-eye-on.svg
  src/app/login/README.md
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/app/signup/layout.tsx
  src/app/signup/page.tsx
  src/components/common/input-form.tsx
  src/components/style/input-style.tsx
  src/hooks/use-login.ts
  src/hooks/use-signup.ts
  src/types/login.ts
  src/types/signup.ts
  tsconfig.json
Labels: feature

#65 [Fix] 모달을 닫은 뒤 스크롤이 안되는 문제 해결
  src/hooks/use-modal.tsx
Labels: bug, Fix

#67 [Feature] 노트 작성/수정 폴더 및 페이지 생성
  src/app/notes/write/README.md
  src/app/notes/write/page.tsx
  src/components/notes/edit.tsx
  src/components/notes/write.tsx
Labels: feature

#74 Feat/note overview
  public/notes/note-list.svg
  src/app/layout.tsx
  src/app/notes/layout.tsx
  src/app/notes/page.tsx
  src/app/notes/write/page.tsx
  src/components/common/README.md
  src/components/notes/list.tsx
  src/components/notes/select.tsx
  src/hooks/README.md
  src/lib/api.ts
  src/store/README.md
  src/store/use-modal-store.tsx
  src/types/notes.ts
  src/types/store.ts
Labels: feature

#76 [Fix] 레이아웃 css 수정 및 로컬스토리지 get 변수 수정
  src/app/notes/layout.tsx
  src/app/notes/page.tsx
Labels: bug, Fix

#78 [Chore] 로컬스토리지 get 변수 변경
  src/components/notes/edit.tsx
  src/components/notes/select.tsx
Labels: Chore

#79 [Feature] api 공통함수 axios로 변경
  package-lock.json
  package.json
  src/lib/api.ts
  src/types/api.ts
Labels: feature

#80 Chore: 노트 모아보기 컴포넌트 변경
  src/app/notes/write/page.tsx
  src/components/notes/edit.tsx
  src/components/notes/write.tsx
Labels: Chore

#81 [Chore] 목표 퍼센트 및 무한스크롤 ref 수정
  src/app/goals/[goalId]/page.tsx
  src/components/goals/prograss-motion.tsx
  src/components/goals/todo-list.tsx
Labels: Chore

#86 [Feature] 노트 수정 페이지 구현
  public/file.svg
  public/globe.svg
  public/markdown-editor/ic-save-link.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/notes/layout.tsx
  src/app/notes/page.tsx
  src/app/notes/write/page.tsx
  src/app/todos/README.md
  src/app/todos/filter.tsx
  src/app/todos/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/side-modal.tsx
  src/components/markdown-editor/markdown-editor.tsx
  src/components/notes/edit.tsx
  src/components/notes/select.tsx
  src/hooks/use-is-note-changed.ts
  src/lib/api.ts
  src/types/todos.ts
  src/utils/README.md
  src/utils/text-from-html.ts
Labels: feature

#90 [Feature] 할일 수정하기 모달
  src/components/common/modal/edit-todo-modal.tsx
Labels: feature

#94 [Fix, Design] 목표 id로 목표 조회하는 api 통신 로직 추가, todo 페이지 레이아웃 스타일 추가
  src/app/notes/page.tsx
  src/app/todos/page.tsx
Labels: Design, Fix

#95 [Chore] 노트 수정, 작성 시 접근 코드 수정
  src/app/notes/write/page.tsx
  src/components/notes/write.tsx
Labels: Chore

#97 [Fix] (노트 작성) 마크다운 에디터 초기 렌더링 시 한 단어만 적히는 에러 수정
  src/components/markdown-editor/markdown-editor.tsx
  src/components/notes/write.tsx
Labels: bug, Fix

#98 [Bug] 목표 드롭다운에 무한 스크롤 기능 추가
  src/app/todos/components/filter.tsx
  src/app/todos/layout.tsx
  src/app/todos/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
  src/components/common/todo-item.tsx
  src/types/todos.ts
Labels: bug

#100 [Feature] 할일 수정 기능 구현, 노트 작성하기 페이지 이동 버튼 생성
  public/todos/ic-note-write.svg
  src/components/common/todo-item.tsx
  src/components/goals/todo-list.tsx
Labels: feature

#104 [Chore] 노트html적용, goal 변수명 수정
  src/app/goals/[goalId]/page.tsx
  src/components/common/modal/side-modal.tsx
  src/components/goals/goal-header.tsx
  src/components/notes/edit.tsx
  src/components/notes/write.tsx
Labels: Chore

#106 [Bug] 할일 추가/수정 모달에서 Input 클릭 시 리액트 에러 해결
  src/components/common/modal/add-todo-modal.tsx
Labels: bug

#108 [Chore] progress 수정
  src/app/goals/[goalId]/page.tsx
  src/components/goals/goal-header.tsx
Labels: Chore

#109 [Fix] 대시보드 제목 링크 추가
  src/app/dashboard/components/body/goal-title-header.tsx
Labels: bug, Fix

#112 [Bug] 할일 페이지 스크롤 / 목표 미표시 문제 해결
  src/app/todos/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
Labels: bug

#113 [Feature] 할 일 수정 모달 추가
  public/slid-to-do.svg
  src/app/dashboard/components/body/todo-list.tsx
  src/app/dashboard/components/header/new-addtodo.tsx
  src/app/loading.tsx
  src/components/common/loading-spinner.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
  src/components/navigation/components/client-sidebar.tsx
  src/components/navigation/components/goal-list.tsx
Labels: feature

#116 [Feature] alert 창 toast 메세지 ui로 변경
  src/app/api/sign-up-api.ts
  src/app/goals/[goalId]/page.tsx
  src/app/login/page.tsx
  src/app/notes/write/page.tsx
  src/app/signup/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
  src/components/notes/edit.tsx
  src/components/notes/write.tsx
Labels: feature

#117 [Deploy] 중간 발표 이전 마지막 배포 자료
  src/components/notes/write.tsx
Labels: deploy

#123 [Test] jest 설치 및 테스트 폴더, api 테스트 코드 추가
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/lib/api.ts
  test/hooks/README.md
  test/lib/api.test.ts
Labels: test
