Repository slid-to-do/slid-to-do-fe, pull requests merged in 2025-08, with the labels that each got.

#133 [Refactor] 피드백 관련 처리
  src/app/goals/[goalId]/page.tsx
  src/app/notes/write/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
  src/components/common/modal/side-modal.tsx
  src/components/goals/goal-header.tsx
  src/components/goals/todo-list.tsx
  src/components/navigation/components/client-sidebar.tsx
  src/components/navigation/components/goal-list.tsx
  src/components/style/utils.ts
  tailwind.config.ts
Labels: refactor

#137 [Refactor, Bug] 할 일&노트 페이지 레이아웃 수정 , 노트 작성 마크다운 가로 스크롤 생기는 현상 수정
  src/app/notes/layout.tsx
  src/app/notes/page.tsx
  src/app/todos/page.tsx
  src/components/common/modal/side-modal.tsx
  src/components/markdown-editor/markdown-editor.tsx
  src/components/notes/edit.tsx
  src/components/notes/select.tsx
Labels: refactor

#140 [Feature] 로그인 유무 확인 Middleware 구현
  src/app/login/page.tsx
  src/app/page.tsx
  src/features/README.md
  src/middleware.ts
  test/hooks/README.md
  test/lib/api.test.ts
Labels: bug, feature

#141 [Feature, Refactor] toast 추가 및 api 호출 로직 분리
  src/__tests__/goals/goals-header.test.tsx
  src/app/api/goal-api.ts
  src/app/api/note-api.ts
  src/app/api/todo-api.ts
  src/app/goals/[goalId]/page.tsx
  src/app/notes/page.tsx
  src/app/notes/write/page.tsx
  src/app/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
  src/components/common/note-save-toast.tsx
  src/components/goals/goal-header.tsx
  src/components/markdown-editor/markdown-editor.tsx
  src/components/navigation/components/goal-modal.tsx
  src/components/notes/write.tsx
  src/types/notes.ts
Labels: feature, refactor

#146 [Refactor]피드백 개선 상황 수정
  src/app/dashboard/components/body/goal-list-body.tsx
  src/app/dashboard/page.tsx
  src/components/navigation/sidebar-container.tsx
Labels: refactor

#149 [Chore] 할일 모달에 useCustomQuery, useCustomMutation 적용
  src/app/api/upload/route.ts
  src/app/todos/page.tsx
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
Labels: Chore

#150 [Rename] login-api,signup-api 폴더 위치 변경
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/signup/page.tsx
  src/lib/auth/login-api.ts
  src/lib/auth/signup-api.ts
  src/middleware.ts
Labels: Rename

#155 [Fix] 할일 추가/수정 모달 버그 수정
  src/components/common/modal/add-todo-modal.tsx
  src/components/common/modal/edit-todo-modal.tsx
Labels: bug, Fix

#156 test: use-toast 훅 테스트 코드 작성
  src/__tests__/hooks/use-toast.test.tsx
Labels: test

#157 [Design] 텍스트가 길어질 경우 말 줄임표 처리 및 인풋 maxLength설정
  src/app/dashboard/components/body/goal-list-body.tsx
  src/app/dashboard/components/body/goal-title-header.tsx
  src/app/goals/[goalId]/page.tsx
  src/app/notes/page.tsx
  src/app/providers/toast-provider.tsx
  src/components/goals/goal-header.tsx
  src/components/navigation/components/goal-modal.tsx
  src/components/navigation/components/sidebar-profile.tsx
  src/components/notes/edit.tsx
  src/components/notes/write.tsx
Labels: bug, Design

#161 [Fix] 노트 작성하기 오류 해결
  src/components/notes/write.tsx
  src/lib/notes/api.ts
Labels: bug, Fix

#162 [Feature] 노트 작성 시 엔터, 최대 글자 수, 스크롤 제한 추가 및 커서 나타나는 범위 수정
  src/components/markdown-editor/markdown-editor.tsx
  src/lib/notes/editor/max-lines.ts
  src/lib/notes/editor/paste-limiter.ts
Labels: feature

#165 [Fix] tab 버튼 활성화 시 이동가능하게 수정
  src/hooks/use-modal.tsx
Labels: bug, Fix

#164 [Refactor] useCustomMutation, Query 적용
  src/__tests__/dashboard/dashboard.test.tsx
  src/__tests__/dashboard/goal-header-container.test.tsx
  src/__tests__/dashboard/goal-todo-container.test.tsx
  src/__tests__/goals/goals-header.test.tsx
  src/__tests__/goals/goals-todo-list.test.tsx
  src/__tests__/goals/goals.test.tsx
  src/app/dashboard/components/body/goal-list-body.tsx
  src/app/dashboard/components/body/goal-title-header.tsx
  src/app/dashboard/components/body/goal-todo-container.tsx
  src/app/dashboard/components/header/header-container.tsx
  src/components/navigation/components/goal-list.tsx
  src/components/navigation/components/goal-modal.tsx
  src/components/navigation/components/sidebar-profile.tsx
  src/middleware.ts
Labels: refactor

#166 [Fix] 목표 페이지 사이드 바 끊김 수정 & 삭제 아이콘 cursor-pointer 적용
  src/app/goals/[goalId]/page.tsx
  src/app/goals/layout.tsx
  src/components/markdown-editor/markdown-editor.tsx
  src/components/notes/write.tsx
Labels: bug, Fix

#168 [Fix] todo 페이지 스피너 적용 / 사이드 모달 긴 내용 줄바꿈 처리
  src/app/todos/page.tsx
  src/components/common/modal/side-modal.tsx
Labels: bug, Chore, Fix

#169 [Fix] 로그인/회원가입 폼 버튼 수정, 회원가입 커버이미지 적용
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/common/input-form.tsx
  src/types/login.ts
Labels: bug, Fix

#171 [Fix] Last QA Feedback 수정 및 적용
  src/app/dashboard/components/body/goal-list-body.tsx
  src/app/dashboard/components/body/todo-list.tsx
  src/app/dashboard/components/header/new-addtodo.tsx
  src/app/dashboard/components/header/progress.tsx
  src/app/goals/[goalId]/page.tsx
  src/components/common/todo-item.tsx
  src/components/goals/todo-list.tsx
  src/components/navigation/components/client-sidebar.tsx
  src/components/navigation/components/goal-list.tsx
  src/components/navigation/sidebar-container.tsx
  src/hooks/use-layout.tsx
  tailwind.config.ts
Labels: bug, Design, Fix

#172 [Fix] QA 피드백 적용
  src/app/goals/[goalId]/page.tsx
  src/components/notes/write.tsx
  src/lib/goals/api.ts
  src/types/goals.ts
Labels: bug, Fix

#173 [Fix] 새목표 500 에러처리
  src/components/navigation/components/goal-modal.tsx
Labels: bug, Fix

#174 [Fix] 사이드바 목표 로딩 추가
  src/app/dashboard/components/body/goal-title-header.tsx
  src/app/dashboard/page.tsx
  src/components/navigation/components/goal-list.tsx
  src/hooks/use-infinite-scroll.ts
  tailwind.config.ts
Labels: bug, Fix

#176 [Fix] Todo 컨텍스트 메뉴 스크롤에 가려지는 문제 해결
  src/components/common/todo-item.tsx
  src/components/goals/todo-list.tsx
Labels: bug, Fix

#192 [Fix] 노트 작성하기 버튼 사라짐이슈 해결
  src/components/common/todo-item.tsx
Labels: bug, Fix

#195 Docs: update README.md
  CONVENTION.md
  README.md
Labels: docs, documentation

#199 [Docs] README 업데이트
  README.md
Labels: docs, documentation

#200 [Docs] readme 프로젝트 기간 추가
  README.md
Labels: docs, documentation
